version: '3.8'

services:
  # Ollama service for embeddings
  ollama:
    image: ollama/ollama:latest
    container_name: langgraph-mem0-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  # Main application - API server
  app:
    build: .
    container_name: langgraph-mem0-app
    depends_on:
      ollama:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./db:/app/db
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - ANTHROPIC_MODEL=${ANTHROPIC_MODEL:-claude-sonnet-4-0}
      - OLLAMA_MODEL=${OLLAMA_MODEL:-nomic-embed-text:latest}
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_EMBEDDING_DIMS=${OLLAMA_EMBEDDING_DIMS:-768}
      - CHROMA_COLLECTION_NAME=${CHROMA_COLLECTION_NAME:-test}
      - CHROMA_DB_PATH=/app/db
      - HOST=0.0.0.0
      - PORT=8000
      - RATE_LIMIT_REQUESTS_PER_MINUTE=${RATE_LIMIT_REQUESTS_PER_MINUTE:-20}
      - RATE_LIMIT_REQUESTS_PER_HOUR=${RATE_LIMIT_REQUESTS_PER_HOUR:-100}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - langgraph-network

  # Optional: Ollama model setup service (runs once to pull models)
  ollama-setup:
    image: ollama/ollama:latest
    container_name: langgraph-mem0-setup
    depends_on:
      ollama:
        condition: service_healthy
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=ollama:11434
    command: >
      sh -c "
        echo 'Pulling nomic-embed-text model...' &&
        ollama pull nomic-embed-text:latest &&
        echo 'Model setup complete!'
      "
    networks:
      - langgraph-network
    restart: "no"

volumes:
  ollama_data:
    driver: local

networks:
  langgraph-network:
    driver: bridge